# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Mod Properties
version = 1.1.0
maven_group = legacy.observers
archives_base_name = legacy-observers

# Dependencies - check https://ornithemc.net/develop for the latest versions
minecraft_version = 1.11.2
minecraft_version_range = mc1.11.x
feather_build = 27
loader_version = 0.16.2
